# Generated by Django 4.0.3 on 2022-03-10 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='changed_at',
            field=models.DateField(auto_now=True),
        ),
    ]
