# Generated by Django 4.0.3 on 2022-03-10 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_measurement_changed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='changed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
